name: CI/CD to Hugging Face

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

  deploy:
    needs: test   
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Clone HF Space
        run: |
          git clone https://huggingface.co/spaces/sancloudmlops/flask-random-fruit hf-space

      - name: Copy files
        run: |
          rsync -av --exclude='.git' --exclude='.github' ./ hf-space/

      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd hf-space
          git config user.email "you@example.com"
          git config user.name "github-actions"
          git add .
          git commit -m "Deploy from GitHub" || echo "No changes"
          git remote set-url origin https://sancloudmlops:$HF_TOKEN@huggingface.co/spaces/sancloudmlops/flask-random-fruit
          git push origin main